spring.datasource.url=jdbc:postgresql://localhost:5432/Bible
spring.datasource.username=CuriousOne
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=5000
